# Generated by Django 4.1 on 2022-08-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_category_restaurantcategory_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='restaurantcategory',
            options={'verbose_name': 'Restaurant Category', 'verbose_name_plural': 'Restaurant Categories'},
        ),
    ]
